version: '3.8'

services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Next_Auth_DB
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - redis_volume:/data
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"

volumes:
  postgres_volume:
  redis_volume:
