version: '3.8'

services:

  # nextjs:
  #   build:
  #     context: ./NextJS
  #     target: dev
  #   command: npm run dev
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - ./NextJS:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - common_network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Next_Auth_DB
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # networks:
    #   - common_network

  redis:
    image: redis:latest
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - redis_volume:/data
    ports:
      - "6379:6379"
    # networks:
    #   - common_network

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    # networks:
    #   - common_network

# networks:
#   common_network:
#     driver: bridge

volumes:
  postgres_volume:
  redis_volume:
